name: Update BTC Data

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Ensure folder exists
        run: mkdir -p public/data

      - name: Fetch APIs
        run: |
          MARKETS=$(curl -s "https://gamma-api.polymarket.com/markets?tag_slug=crypto&limit=1000&active=true")
          BTC=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd&include_24hr_change=true")

          echo "{
            \"markets\": $MARKETS,
            \"btc\": $BTC,
            \"updated\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"
          }" > public/data/data.json

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add public/data/data.json

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "auto update data"
            git push origin main
          fi
